;; Profile for LaTeX extra packages
(specifications->manifest
 '(
   "texlive-listing"
   "texlive-hyperref"
   "texlive-wrapfig"
   "texlive-cm"
   "texlive-cm-super"
   "texlive-cm-unicode"
   "texlive-pgf"
   "texlive-pgfplots"
   "texlive-gnuplottex"
   "texlive-beamer"
   "texlive-amsmath"
   "texlive-amsfonts"
   "texlive-roboto"
   "texlive-dvisvgm"
   "texlive-dvisvgm-bin"
   ))
