;; Profile for Python web server development
(specifications->manifest
 '(
   "python-fastapi"
   "python-uvicorn"
   "python-websockets"
   "python-socketio"
   "python-jsonschema"
   "python-jinja2"
   "python-loguru"
   "python-celery"
   "python-filelock"
   "python-redis"
   "python-psycopg2"
   "python-arrow"
   "python-bcrypt"
   "python-bleach"
   "python-ratelimiter"
   ))
