# Playback
SPACE cycle pause
LEFT no-osd seek -5
RIGHT no-osd seek +5

# Screen
ENTER cycle fullscreen # toggle fullscreen
MBTN_MID cycle fullscreen
r cycle_values video-rotate 90 180 270 0

# Volume
m cycle mute
MUTE cycle mute
UP add volume +5
DOWN add volume -5
