# basic configuration
backend = "glx";
vsync = true;

# EXWM specific
use-ewmh-active-win = true;
shadow = false;

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 5;

inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;

# Performance hack
unredir-if-possible = true;
unredir-if-possible-exclude = [
    "class_g = 'mpv'",
];

# Intel-specific tweaks
xrender-sync-fense = true;

# Replace old partial-screen updates
use-damage = true;
