#!/bin/sh

# Source .profile for commmon env vars
. "$HOME/.profile"

# Disable access control for the current user
xhost +SI:localuser:$USER

# Make Java apps aware this is non-reparenting WM
export _JAVA_AWT_WM_NONREPARENTING=1

# Load X11 settings
xrdb $XDG_CONFIG_HOME/X11/xresources
xsettingsd &

# Enable screen compositing
picom --config $XDG_CONFIG_HOME/picom/picom.conf &

# Enbable screen locking on suspend
xss-lock -- slock &

# Use Emacs for text edit
export VISUAL=emacsclient
export EDITOR="$VISUAL"

# Debug purpose
#exec xterm

# Set input method Environment Variables
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
export INPUT_METHOD=xim
export SDL_IM_MODULE=xim

# Describe this graphical session to desktop services and portals.
export XDG_CURRENT_DESKTOP=EXWM
export XDG_SESSION_DESKTOP=exwm
export XDG_SESSION_TYPE=x11

# Start EXWM
# exec dbus-launch --exit-with-session emacs -mm --debug-init -f exwm-enable
# exec dbus-launch --exit-with-session emacs -mm -f exwm-wm-mode
# exec dbus-launch --exit-with-session sh -c 'fcitx5 -d & exec emacs -mm -f exwm-wm-mode'
exec dbus-launch --exit-with-session sh -c '
    # Make the X11/EXWM environment available to D-Bus-activated services,
    # particularly xdg-desktop-portal and its GTK backend.
    dbus-update-activation-environment \
        DISPLAY \
        XAUTHORITY \
        XDG_RUNTIME_DIR \
        XDG_CURRENT_DESKTOP \
        XDG_SESSION_DESKTOP \
        XDG_SESSION_TYPE \
        XDG_DATA_DIRS \
        FLATPAK_USER_DIR \
        PATH

    fcitx5 -d
    exec emacs -mm -f exwm-wm-mode
'
